spring.application.name=modulo-b

# Url para apontar para o mesmo arquivo de banco do Módulo A, forma que achei de
# compartilhar os dados entre os modulos
spring.datasource.url=jdbc:h2:file:C:/Users/rebim/OneDrive/Documentos/anbima-desafio/modulo-a/pedidosdb;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

# Modulo A roda na porta 8080, entao mudei o B para a porta 8081 para evitar conflito
server.port=8081