spring.application.name=modulo-a

# Banco H2 em memoria para desenvolvimento
spring.datasource.url=jdbc:postgresql://localhost:5432/pedidosdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Console H2 acessivel em localhost:8080/h2-console
spring.h2.console.enabled=true

# Hibernate cria as tabelas automaticamente pelas entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configura o Rabbitmq
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest